sources:
- title: Meditations (Gregory Hays translation, 2002)
  type: book
  accessed: '2026-03-22'
- title: Meditations (George Long translation, 1862)
  type: book
  url: https://www.gutenberg.org/ebooks/2680
  accessed: '2026-03-22'
- title: How to Think Like a Roman Emperor (Donald Robertson, 2019)
  type: book
  accessed: '2026-03-22'
