sources:
  - title: >
      Sketch of the Analytical Engine Invented by Charles Babbage, with Notes
      by the Translator (Ada Lovelace, 1843)
    type: article
    url: https://www.fourmilab.ch/babbage/sketch.html
    accessed: '2026-03-23'
  - title: >
      Ada, the Enchantress of Numbers: A Selection from the Letters of Lord
      Byron's Daughter and Her Description of the First Computer
    type: book
    url: https://archive.org/details/adaenchantressof0000love
    accessed: '2026-03-23'
  - title: >
      Ada Lovelace: The Making of a Computer Scientist (Hollings, Martin, Rice, 2018)
    type: book
    url: https://www.bodleian.ox.ac.uk/whats-on/online/ada-lovelace
    accessed: '2026-03-23'
