sources:
- title: The Secret History of the Mongols
  url: https://en.wikipedia.org/wiki/Secret_History_of_the_Mongols
  accessed: '2026-03-25'
- title: The Art of War for Emperors (Genghis Khan's military doctrines)
  accessed: '2026-03-25'
- title: 'The Mongol Empire: A Historical Encyclopedia'
  accessed: '2026-03-25'
