sources:
- title: 'Rani Lakshmibai: Jhansi in the Rebellion of 1857'
  url: https://en.wikipedia.org/wiki/Rani_Lakshmibai
  accessed: '2026-03-25'
- title: The Indian War of Independence 1857 (V.D. Savarkar)
  accessed: '2026-03-25'
- title: 'British Records of the 1857 Mutiny: Rani of Jhansi'
  url: https://www.bl.uk/collections/1857-indian-mutiny
  accessed: '2026-03-25'
