sources:
  - title: TODO source 1
    type: book
    accessed: "2026-01-01"
  - title: TODO source 2
    type: book
    accessed: "2026-01-01"
  - title: TODO source 3
    type: book
    accessed: "2026-01-01"
